config/routes.rb
Bc4::Application.routes.draw do

 

  namespace :admin do
    resources :report_tags
  end

  namespace :admin do
    resources :sub_metrics
  end

  
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :password_resets
  resources :users
  resources :newsletters

  

  match 'wed' => 'wed/wed#dashboard', via: :get
  match 'wed/dashboard' => 'wed/wed#dashboard', via: :get, :as => :wed_dashboard
  match 'wed/score-card' => 'wed/wed#score_card', via: :get, :as => :score_card
  match 'wed/latest-report' => 'wed/wed#latest_report', via: :get, :as => :latest_report
  match 'wed/progress-chart' => 'wed/wed#progress_chart', via: :get, :as => :progress_chart
  match 'wed/peer-comparison' => 'wed/wed#peer_comparison', via: :get, :as => :peer_comparison
  match 'wed/best-practice' => 'wed/wed#best_practice', via: :get, :as => :best_practice
  match 'wed/results-table' => 'wed/wed#results_table', via: :get, :as => :results_table
  match 'wed/consultancy' => 'wed/wed#consultancy', via: :get, :as => :wed_consultancy
  match 'wed/wen' => 'wed/wed#wen', via: :get, :as => :wed_wen

  match 'admin' => 'admin/admin#dashboard', via: :get, :as => :admin_dashboard
  match 'admin/advanced-search' => 'admin/admin#advanced_search', via: :get, :as => :admin_advanced_search
  match 'admin/manage-report/:id' => 'admin/reports#manage_report', via: :get, :as => :manage_report
  match 'admin/emails' => 'admin/system_emails#index', via: :get, :as => :admin_emails

  match 'admin/cmsdesk' => 'admin/cms_desk#index', via: :get, :as => :cms_desk
  match 'admin/cmsdesk/web' => 'web/pages#index', via: :get, :as => :cms_desk_web_pages
  match 'admin/cmsdesk/web/new' => 'web/pages#new', via: :get, :as => :cms_desk_new_web_page
  match 'admin/cmsdesk/web/:id/edit' => 'web/pages#edit', via: :get, :as => :cms_desk_edit_web_page
  match 'admin/cmsdesk/commentaries' => 'admin/commentaries#index', via: :get, :as => :cms_desk_commentaries
  match 'admin/cmsdesk/bctips' => 'admin/bctips#index', via: :get, :as => :cms_desk_bctips

  match 'wed/company-profile/:id' => 'wed/wed#company_profile', via: :get, :as => :company_profile
  match 'wed/account/my-peers' => 'wed/wed#my_peers', via: :get, :as => :my_peers
  match 'wed/account/my-account' => 'wed/wed#my_account', via: [:get], :as => :my_account
  match 'wed/account/my-account-update' => 'wed/wed#my_account_update', via: [:post], :as => :my_account_update

  match 'wed/search' => 'wed/wed#search', via: :get, :as => :wed_search
  match 'wed/advanced-search' => 'wed/wed#advanced_search', via: :get, :as => :wed_advanced_search

  match 'wed/latest_report/download_pdf' => 'admin/reports#generate_report_pdf', via: :get, :as => :download_report_pdf

  namespace :web do
    resources :widgets
    resources :pages, only: [:index, :new, :create]
    resources :pages, path: "", except: [:index, :new, :create]
  end

  namespace :admin do

    resources :users, :roles
    resources :system_emails

    resources :companies do
      collection do
        post :best_practice_all
      end

      resources :reports
    end

    resources :company_types, :company_statuses, :sectors, :regions, :countries, :subscriptions
    resources :metrics do
    end

    resources :reports do
      resources :notes
      resources :metrics
      resources :screengrabs

      collection do
      end
    end
    resources :projects do
      resources :reports
    end

    resources :report_states, :report_types, :report_tags
  
    resources :bctips, :commentaries

    resources :best_practices do
      resources :screengrabs  
    end
  end

  

    

  unless Web::Page.find_by_url("home").nil?
      root 'web/pages#show', :id => Web::Page.find_by_url("home").id
  else

    root 'web/pages#index'
  end

  get '*id', to: 'web/pages#show', as: :page

  

  
  
end

app/controllers/wed/wed_controller.rb
class Wed::WedController < ApplicationController
  layout 'wed/wed'
  respond_to :js, :html, :json
  # respond_to :js, :html, :only => :best_practice 

  # to do : add custom layout 2 columns
  before_action :authorize
  before_action :get_companies, only: [:results_table, :my_peers, :advanced_search]
  before_action :get_my_peers, only: [:dashboard, :company_profile, :score_card, :progress_chart, :my_peers, :peer_comparison]

  

  def dashboard

    @page_title = "Latest from Bowen Craggs & Co"
    @page_lead = "Our database allows you to view the performance of your company's website, as measured by the 
            Financial Times Bowen Craggs Index of corporate website effectiveness. You can choose up to 10 peer 
            companies to compare against, see charts and reports for all companies, identify best practice, and 
            view your own site's progress."

    @companies = Admin::Company.paginate :page => params[:page],
                :limit => 3        

    render layout: 'wed/two_column'        
  end


  def score_card
    @page_title = "Score Card"
    @page_lead = "Lorem itsum Lorem itsum Lorem itsum Lorem itsum Lorem itsum"

    @metrics = Admin::Metric.order(:number)
    # @my_peers = Admin::Company.find(current_user.user_peer_companies.map(&:company_id))
    # @metrics = @latest_report.report_type.metric_report_types.order(:number)

  end


  def latest_report
    @page_title = "Latest Reports"
    @page_lead = "Explore, download and share your current report whole or in parts; retrieve earlier versions; and check other companies’ reports."

    ## current user's company's latest report
    # check if there is report id params changed, and get report data according to id
    # @latest_report = current_user.company.latest_report
    @company_reports = current_user.company.reports.order('publish_date desc')
    
    unless params[:id].nil?
      @latest_report = @company_reports.find(params[:id])
    else
      @latest_report = @company_reports.first
    end

    
    # @report_type_metrics = @latest_report.report_type.metric_report_types.order(:number)
    # debugger
    @report_metrics = @latest_report.reports_metrics.includes(:metric).order('metrics.number asc')
    # debugger

    # check if there is metric params to search for
    # @current_metric = @metrics.find(params[:metric_id])
    #@first_metric = @metrics.first
    # debugger
  end

  def export_latest_report(format)
    
  end


  def progress_chart
    @page_title = "Progress Chart"
    @page_lead = "Lorem itsum Lorem itsum Lorem itsum Lorem itsum Lorem itsum"

    if current_user
      # @company = current_user.company
      @reports = @company.reports if @company.reports.present?

      @report_years = @reports.order(:publish_date).map(&:publish_date)
      
      @yr = @report_years.map {|d| 
        d.strftime "%Y" 
      }


      @reports.each do |report|
        @metrics = report.reports_metrics
      end
      # @metrics = @reports.first.reports_metrics
      debugger
    end

  end


  def peer_comparison
    @page_title = "Peer Comparison"
    @page_lead = "Lorem itsum Lorem itsum Lorem itsum Lorem itsum Lorem itsum"

    @metrics = Admin::Metric.order(:number)
    # @my_peers = @my_peers.all(:condition => '')
    # debugger
  end


  def best_practice
    @page_title = "Best Practice"
    @page_lead = "Lorem itsum Lorem itsum Lorem itsum Lorem itsum Lorem itsum"

    # top 10 companies order by each metrics scores
    @metrics = Admin::Metric.roots.order(:number)
    @companies = Admin::Company.order(:name).limit(10)

    
    
    
  end


  def results_table
    @page_title = "Results Table"
    @page_lead = "Lorem itsum Lorem itsum Lorem itsum Lorem itsum Lorem itsum"
    @companies = @companies.limit(10)
    @company_types = Admin::CompanyType.all
    @company_sectors = Admin::Sector.all
    @company_regions = Admin::Region.all
    @company_countries = Admin::Country.all

  end

  def consultancy
    @page_title = "Consultancy"
    @page_lead = "Lorem itsum Lorem itsum Lorem itsum Lorem itsum Lorem itsum"

    render layout: 'wed/two_column'        
  end


  def wen
    @page_title = "Web Effectiveness Network (WEN)"
    @page_lead = "Lorem itsum Lorem itsum Lorem itsum Lorem itsum Lorem itsum"

    render layout: 'wed/two_column'        
  end


  def company_profile
    @page_title = "Company Profile"
    @page_lead = ""

    @company = Admin::Company.find(params[:id])
    @reports = @company.reports if @company.reports.present?
    @latest_report = @company.reports.order(:created_at).last
    # @report_type_metrics = @latest_report.report_type.metric_report_types.order(:number)
    @report_metrics = @latest_report.reports_metrics.includes(:metric).order('metrics.number asc')
    # debugger
    # @first_metric = @metrics.first
    unless @reports.nil?
      @report_years = @reports.order(:publish_date).map(&:publish_date).compact
        
      @yr = @report_years.map {|d| 
        d.strftime "%Y" 
      }
    end
  end

  def my_peers
    @page_title = "My Peers"
    @page_lead = "Use the My Peers tab to refine your list of peer companies. You can select up to ten active peers 
          at any one time and these will appear as comparator companies on charts throughout the system.
          If you are your company’s primary super-user your list of peer companies will be used as a suggested first list for 
          any new company users. As a company user, you will inherit your super-user’s list as an initial suggestion, but are 
          free to edit and produce your own list."    

    # temp, TO DO:: get my peer companies
    
  end

  def my_account_update
    if current_user
      debugger
      current_user.firstname = params[:firstname]
      current_user.lastname = params[:lastname]
      current_user.email = params[:email]
      current_user.job_title = params[:job_title]

      # if no password entered , need to skip password field
      if params[:current_password].present?
        if current_user.authenticate(params[:password])
          current_user.password = params[:new_password]
          current_user.confirm_password = params[:confirm_password]
        end  
      end 

      if current_user.save
        format.html { redirect_to my_account_url, notice: 'User Information updated' }
      else
        
        flash.now.alert = "Please Check inputs"
        render "new"

      end
    end
  end

  def my_account
    @page_title = "My Account"
    @page_lead = "Use the My account tab to update your account details, change your password or amend your e-mail preferences."

  end


  def search
    @page_title = "Search"
  end


  def advanced_search
    @page_title = "Advanced Search"
    

    render layout: 'wed/two_column'

  end

  def download_report_pdf
      @report = params[:report_id]
    # debugger
    
  end


  private

  def get_companies
    @companies = Admin::Company.all
  end

  def set_company
    # @companies = Admin::Company.all    
    @my_company = current_user.company
  end

  def get_my_peers
    # TO DO :: GET MY PEERS
    # @my_peers = Admin::Company.find(current_user.user_peer_companies.map(&:company_id))
    @my_peers = current_user.peer_companies
    
  end
end

app/helpers/wed/application_helper.rb
module Wed::ApplicationHelper
end

app/helpers/wed/wed_helper.rb
module Wed::WedHelper
end

app/views/layouts/wed/_footer.html.erb
<footer>
  <div class="utility">
    <ul>
        <li><a href="#" id="go-top">
          <span>Top of page</span></a>
        </li>
        <li>
          <a href="/privacy-cookies/" class="cc-privacy-link">
            <span>Privacy &amp; cookies</span>
          </a>
        </li>
        <li><a href="http://www.skyron.co.uk" target="_blank"><span>Designed by Skyron</span></a></li>
    </ul>
    <span>&copy; Bowen Craggs &amp; Co. Ltd. 2013</span>
  </div>
</footer>

app/views/layouts/wed/_header.html.erb
<header>
  <div class="navbar" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" 
        	data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to wed_dashboard_path, :class => "navbar-brand" do %>
          <img src="/assets/BC-database-logo_251-wide.png" alt="logo" />
        <% end %>
      </div>
      
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
          
          <li><%= link_to "Logout", logout_path %></li>
        <% else %>
          <li><%= link_to "Log In", new_session_path %></li>
         <% end %>
        <%# if user_signed_in? %>
          <li><%#= link_to "My Account", edit_user_registration_path %></li>
          <li><%#= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <%# end %>
        <li>
          <%= link_to admin_dashboard_path do %>
            <span>Admin</span>
          <% end %>
        </li>
        <li>
          <%= link_to wed_advanced_search_path do %>
            <span>Advanced search</span>
          <% end %>
        </li>
        <li>
          <form class="navbar-form navbar-right">
          <div class="form-group">
            <input type="text" placeholder="Search" class="form-control">
            <input type="submit" class="search" />
          </div>
        </form>
        </li>
      </ul>
    </div>
  </div>


  <%= render 'wed/wed/partials/client_bar' %>
  <!-- <div class="container">
   
  </div> -->
  <nav class="main-nav" role="main">
      <ul id="main-navigation">
        <li class="dashboard">
          <%= link_to "Dashboard", wed_dashboard_path %>
        </li>
        <li class="score-card">
          <%= link_to "Score card", score_card_path %>
        </li>
        <li class="latest-report">
          <%= link_to "Latest Report", latest_report_path %>
        </li>
        <li class="progress-chart">
          <%= link_to "Progress Chart", progress_chart_path %>
        </li>
        <li class="peer-comparison">
          <%= link_to "Peer Comparison", peer_comparison_path %>
        </li>
        <li class="best-practice">
          <%= link_to "Best Practice", best_practice_path %>
        </li>
        <li class="results-table">
          <%= link_to "Results Table", results_table_path %>
        </li>
        <li class="consultancy">
          <%= link_to "Consultancy", wed_consultancy_path %>
        </li>
        <li class="wen">
          <%= link_to "WEN", wed_wen_path %>
        </li>
      </ul>
  </nav>

</header>

app/views/layouts/wed/_login_header.html.erb
<header>
  <div class="navbar" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" 
        	data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to wed_dashboard_path, :class => "navbar-brand" do %>
          <img src="/assets/BC-database-logo_251-wide.png" alt="logo" />
        <% end %>
      </div>
      
      <ul class="nav navbar-nav pull-right">
        <li>
          <%= link_to page_path('contact-us') do %>
            <span>Contact</span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

</header>

app/views/layouts/wed/_meta_head.html.erb
<title>Bc4</title>

app/views/layouts/wed/two_column.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/wed/meta_head' %>
  <%= stylesheet_link_tag "global", "wed", media: "all" %>  
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		
		<%= render 'layouts/wed/header' %>	
		<!-- page header -->
		<div class="row">
			<div class="col-sm-9">
				<% if content_for(:page_header) %>	
					<%= yield :page_header %>
				<% else %>
					<div class="page-header">
						<h1><%= @page_title || "Page Title" %></h1>
						<% unless @page_lead.blank? %>
				    	<p class="lead"><%= @page_lead %></p>
				    <% end %>
				  </div>
				<% end %>	

				<!-- content -->
				<%= yield %>
			</div>
			<div class="col-sm-3 sidebar">
				<%= yield :sidebar %>
			</div>
		</div>
		<%= render 'layouts/wed/footer' %>
	</div>	

	<%= javascript_include_tag "application" %>
	<%= yield :scripts %>
	
</body>
</html>

app/views/layouts/wed/wed.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/wed/meta_head' %>
  <%= stylesheet_link_tag "global", "wed", "http://fonts.googleapis.com/css?family=EB+Garamond", media: "all" %>  
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		
		<%= render 'layouts/wed/header' %>	
		<!-- page header -->
		<% if content_for(:page_header) %>	
			<%= yield :page_header %>
		<% else %>
			<div class="page-header">
				<h1><%= @page_title || "Page Title" %></h1>
				<% unless @page_lead.blank? %>
		    	<p class="lead"><%= @page_lead %></p>
		    <% end %>
		  </div>
		<% end %>	

		<!-- content -->
		<%= yield %>
		<%= render 'layouts/wed/footer' %>
	</div>	

	<%= javascript_include_tag "application", "wed" %>
	<%= yield :scripts %>
	
</body>
</html>