config/routes.rb
Bc4::Application.routes.draw do

 

  namespace :admin do
    resources :report_tags
  end

  namespace :admin do
    resources :sub_metrics
  end

  
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :password_resets
  resources :users
  resources :newsletters

  

  match 'wed' => 'wed/wed#dashboard', via: :get
  match 'wed/dashboard' => 'wed/wed#dashboard', via: :get, :as => :wed_dashboard
  match 'wed/score-card' => 'wed/wed#score_card', via: :get, :as => :score_card
  match 'wed/latest-report' => 'wed/wed#latest_report', via: :get, :as => :latest_report
  match 'wed/progress-chart' => 'wed/wed#progress_chart', via: :get, :as => :progress_chart
  match 'wed/peer-comparison' => 'wed/wed#peer_comparison', via: :get, :as => :peer_comparison
  match 'wed/best-practice' => 'wed/wed#best_practice', via: :get, :as => :best_practice
  match 'wed/results-table' => 'wed/wed#results_table', via: :get, :as => :results_table
  match 'wed/consultancy' => 'wed/wed#consultancy', via: :get, :as => :wed_consultancy
  match 'wed/wen' => 'wed/wed#wen', via: :get, :as => :wed_wen

  match 'admin' => 'admin/admin#dashboard', via: :get, :as => :admin_dashboard
  match 'admin/advanced-search' => 'admin/admin#advanced_search', via: :get, :as => :admin_advanced_search
  match 'admin/manage-report/:id' => 'admin/reports#manage_report', via: :get, :as => :manage_report
  match 'admin/emails' => 'admin/system_emails#index', via: :get, :as => :admin_emails

  match 'admin/cmsdesk' => 'admin/cms_desk#index', via: :get, :as => :cms_desk
  match 'admin/cmsdesk/web' => 'web/pages#index', via: :get, :as => :cms_desk_web_pages
  match 'admin/cmsdesk/web/new' => 'web/pages#new', via: :get, :as => :cms_desk_new_web_page
  match 'admin/cmsdesk/web/:id/edit' => 'web/pages#edit', via: :get, :as => :cms_desk_edit_web_page
  match 'admin/cmsdesk/commentaries' => 'admin/commentaries#index', via: :get, :as => :cms_desk_commentaries
  match 'admin/cmsdesk/bctips' => 'admin/bctips#index', via: :get, :as => :cms_desk_bctips

  match 'wed/company-profile/:id' => 'wed/wed#company_profile', via: :get, :as => :company_profile
  match 'wed/account/my-peers' => 'wed/wed#my_peers', via: :get, :as => :my_peers
  match 'wed/account/my-account' => 'wed/wed#my_account', via: [:get], :as => :my_account
  match 'wed/account/my-account-update' => 'wed/wed#my_account_update', via: [:post], :as => :my_account_update

  match 'wed/search' => 'wed/wed#search', via: :get, :as => :wed_search
  match 'wed/advanced-search' => 'wed/wed#advanced_search', via: :get, :as => :wed_advanced_search

  match 'wed/latest_report/download_pdf' => 'admin/reports#generate_report_pdf', via: :get, :as => :download_report_pdf

  namespace :web do
    resources :widgets
    resources :pages, only: [:index, :new, :create]
    resources :pages, path: "", except: [:index, :new, :create]
  end

  namespace :admin do

    resources :users, :roles
    resources :system_emails

    resources :companies do
      collection do
        post :best_practice_all
      end

      resources :reports
    end

    resources :company_types, :company_statuses, :sectors, :regions, :countries, :subscriptions
    resources :metrics do
    end

    resources :reports do
      resources :notes
      resources :metrics
      resources :screengrabs

      collection do
      end
    end
    resources :projects do
      resources :reports
    end

    resources :report_states, :report_types, :report_tags
  
    resources :bctips, :commentaries

    resources :best_practices do
      resources :screengrabs  
    end
  end

  

    

  unless Web::Page.find_by_url("home").nil?
      root 'web/pages#show', :id => Web::Page.find_by_url("home").id
  else

    root 'web/pages#index'
  end

  get '*id', to: 'web/pages#show', as: :page

  

  
  
end

app/views/layouts/admin/_footer.html.erb
<div class="container">
	<div class="footer">
		<ul class="nav nav-pills pull-left">
      <li>Bowen Craggs &amp; CO. Ltd. 2013</li>
      <li>Visit<a href="#">Bowencraggs.com</a></li>
    </ul>
		
    <span class="pull-right">
    	<img src="/assets/footer-logo.jpg" alt="logo" />
    </span>
	</div>
</div>

app/views/layouts/admin/_header.html.erb
<header>
  <div class="navbar" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" 
          data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to admin_dashboard_path, :class => "navbar-brand" do %>
          <img src="/assets/BC-database-logo_251-wide.png" alt="logo" />
        <% end %>
      </div>
      
      <ul class="nav navbar-nav pull-right">
        
        <% if current_user %>  
          <li><%= link_to "Logout", logout_path %></li>
        <% end %>  
        <li>
          <%= link_to admin_advanced_search_path do %>
            <span>Advanced search</span>
          <% end %>
        </li>
        <li>
          <form class="navbar-form navbar-right">
          <div class="form-group">
            <input type="text" placeholder="Search" class="form-control">
            <input type="submit" class="search" />
          </div>
          
        </form>
        </li>
      </ul>
    </div>
  </div>

  <!-- <div class="container">
    <%# if user_signed_in? %>
      <%#= current_user.email  %>
    <%# end %>
  </div> -->


  <nav class="main-nav" role="main">
    
      <ul id="main-navigation">
        <li class="dashboard">
          <%= link_to "Dashboard", admin_dashboard_path %>
        </li>
        <li>
          <%= link_to "Companies", admin_companies_path %>
        </li>
        <li>
          <%= link_to "Projects/Reports", admin_projects_path %>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <li>
          <%= link_to "Emails", admin_emails_path %>
        </li>
        <li>
          <%= link_to "CMS", cms_desk_path %>
        </li>
      </ul>

      <%= content_for(:sub_menu) %>
    
  </nav>
</header>

app/views/layouts/admin/_meta_head.html.erb
<title>Bc4</title>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/admin/meta_head' %>
  <%= stylesheet_link_tag "global", "admin", media: "all" %>  
  <%= csrf_meta_tags %>
</head>
<body>

		<div class="container">
			<%= render 'layouts/admin/header' %>

			<%= yield %>
			<%= render 'layouts/wed/footer' %>
		</div>

	<%= javascript_include_tag "application", "admin" %>
	<%= yield :scripts %>
	
</body>
</html>

app/views/layouts/admin/cms_desk.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/admin/meta_head' %>
  <%= stylesheet_link_tag "global", "admin", media: "all" %>  
  <%= csrf_meta_tags %>
</head>
<body>

		<div class="container">
			<%= render 'layouts/admin/header' %>
			<h2>This is cms layout to style</h2>
				<%= yield %>
			<%= render 'layouts/wed/footer' %>
		</div>

	<%= javascript_include_tag "application", "admin" %>
	<%= yield :scripts %>
	
</body>
</html>