config/routes.rb
Bc4::Application.routes.draw do

 

  namespace :admin do
    resources :report_tags
  end

  namespace :admin do
    resources :sub_metrics
  end

  
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :password_resets
  resources :users
  resources :newsletters

  

  match 'wed' => 'wed/wed#dashboard', via: :get
  match 'wed/dashboard' => 'wed/wed#dashboard', via: :get, :as => :wed_dashboard
  match 'wed/score-card' => 'wed/wed#score_card', via: :get, :as => :score_card
  match 'wed/latest-report' => 'wed/wed#latest_report', via: :get, :as => :latest_report
  match 'wed/progress-chart' => 'wed/wed#progress_chart', via: :get, :as => :progress_chart
  match 'wed/peer-comparison' => 'wed/wed#peer_comparison', via: :get, :as => :peer_comparison
  match 'wed/best-practice' => 'wed/wed#best_practice', via: :get, :as => :best_practice
  match 'wed/results-table' => 'wed/wed#results_table', via: :get, :as => :results_table
  match 'wed/consultancy' => 'wed/wed#consultancy', via: :get, :as => :wed_consultancy
  match 'wed/wen' => 'wed/wed#wen', via: :get, :as => :wed_wen

  match 'admin' => 'admin/admin#dashboard', via: :get, :as => :admin_dashboard
  match 'admin/advanced-search' => 'admin/admin#advanced_search', via: :get, :as => :admin_advanced_search
  match 'admin/manage-report/:id' => 'admin/reports#manage_report', via: :get, :as => :manage_report
  match 'admin/emails' => 'admin/system_emails#index', via: :get, :as => :admin_emails

  match 'admin/cmsdesk' => 'admin/cms_desk#index', via: :get, :as => :cms_desk
  match 'admin/cmsdesk/web' => 'web/pages#index', via: :get, :as => :cms_desk_web_pages
  match 'admin/cmsdesk/web/new' => 'web/pages#new', via: :get, :as => :cms_desk_new_web_page
  match 'admin/cmsdesk/web/:id/edit' => 'web/pages#edit', via: :get, :as => :cms_desk_edit_web_page
  match 'admin/cmsdesk/commentaries' => 'admin/commentaries#index', via: :get, :as => :cms_desk_commentaries
  match 'admin/cmsdesk/bctips' => 'admin/bctips#index', via: :get, :as => :cms_desk_bctips

  match 'wed/company-profile/:id' => 'wed/wed#company_profile', via: :get, :as => :company_profile
  match 'wed/account/my-peers' => 'wed/wed#my_peers', via: :get, :as => :my_peers
  match 'wed/account/my-account' => 'wed/wed#my_account', via: [:get], :as => :my_account
  match 'wed/account/my-account-update' => 'wed/wed#my_account_update', via: [:post], :as => :my_account_update

  match 'wed/search' => 'wed/wed#search', via: :get, :as => :wed_search
  match 'wed/advanced-search' => 'wed/wed#advanced_search', via: :get, :as => :wed_advanced_search

  match 'wed/latest_report/download_pdf' => 'admin/reports#generate_report_pdf', via: :get, :as => :download_report_pdf

  namespace :web do
    resources :widgets
    resources :pages, only: [:index, :new, :create]
    resources :pages, path: "", except: [:index, :new, :create]
  end

  namespace :admin do

    resources :users, :roles
    resources :system_emails

    resources :companies do
      collection do
        post :best_practice_all
      end

      resources :reports
    end

    resources :company_types, :company_statuses, :sectors, :regions, :countries, :subscriptions
    resources :metrics do
    end

    resources :reports do
      resources :notes
      resources :metrics
      resources :screengrabs

      collection do
      end
    end
    resources :projects do
      resources :reports
    end

    resources :report_states, :report_types, :report_tags
  
    resources :bctips, :commentaries

    resources :best_practices do
      resources :screengrabs  
    end
  end

  

    

  unless Web::Page.find_by_url("home").nil?
      root 'web/pages#show', :id => Web::Page.find_by_url("home").id
  else

    root 'web/pages#index'
  end

  get '*id', to: 'web/pages#show', as: :page

  

  
  
end

app/models/admin/project.rb
# == Schema Information
#
# Table name: projects
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  publish_date    :date
#  ft_index        :boolean
#  in_result_table :boolean
#  can_compare     :boolean
#  reports_count   :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class Admin::Project < ActiveRecord::Base
	attr_accessible :id, :name, :publish_date, :ft_index, :in_result_table, :can_compare, :reports_count,
						:reports_attributes, :created_at, :updated_at

	self.table_name = "projects"
	
	has_many :reports
	accepts_nested_attributes_for :reports, allow_destroy: true
	
	scope :published, -> { where('publish_date IS NOT NULL') }  
	scope :recent_projects, -> { order ('created_at desc').limit(10)}
	# custom associations
	# has_many :recent_reports,
 	#    -> { order('created_at desc').limit(2) },
 	#    class_name: "Report"

 	# to do
 	# - scope publishd projects
 	# - scope ft-index-projects


end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Admin::Project.published
    @companies = Admin::Company.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Admin::Project.new
    # 5.times do
    #   @project.reports.build
    # end
  end

  # GET /projects/1/edit
  def edit

  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Admin::Project.new(project_params)
debugger
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Admin::Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      # debugger
      params.require(:admin_project).permit(:name, :publish_date, :ft_index, :in_result_table, :can_compare, :reports_count,
        reports_attributes: [:name, :company_id, :report_type_id, :report_state_id]
        )
    end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<% content_for :sub_menu do %>
  <%= render "admin/shared/projects_sub_menu" %>
<% end %>


<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <article>
    <section>
      <fieldset>
        <%= f.input :name, :label => 'Project Name',
            :input_html => {:class => ''} %>
      </fieldset>  
      <fieldset>  
        <%= f.input :publish_date, :as => :string, :input_html => { :value => f.object.publish_date} %>
        
      </fieldset>
      <fieldset>  
        <%= f.input :ft_index, as: :radio_buttons %>
      </fieldset>
      <fieldset>  
        <%= f.input :in_result_table, as: :radio_buttons %>
      </fieldset>
      <fieldset>
        <%= f.input :can_compare, as: :radio_buttons %>
      </fieldset>
    </section>
  </article>      

  <article>
    <section>

      <header>
        <h4>Reports</h4>
      </header>

      <div action="/admin/reports" method="post" class="test" id="project-new-report-form">
        <fieldset>
          <label>Company</label>
          <div class="col-sm-4">
            <%= select_tag "project-new-report-companies", options_from_collection_for_select(Admin::Company.order(:name), "id", "name"),
             :prompt => "Companies" %>
          </div>
        </fieldset>
        <fieldset>
          <label>Report Type</label>
          <div class="col-sm-4">
            <%= select_tag "project-new-report-type", options_from_collection_for_select(Admin::ReportType.order(:name), "id", "name"),
             :prompt => "Report Type" %>
          </div>
        </fieldset>
        <fieldset>
          <label>Assigned To</label>
          <div class="col-sm-4">
            <!-- to do multiple select -->
            <%= select_tag "project-new-report-assigned_to", options_from_collection_for_select(User.order(:username), "id", "username"),
             :prompt => "Editors" %>
          </div>
        </fieldset>
        <fieldset>  
          <label>Report Title</label>
          <div class="col-sm-4">
            <%= text_field_tag "project-new-report-title" %>
          </div>
        </fieldset>
      </div>
    </section>
    <div class="form-actions">
      <%#= link_to "#", :class => 'btn btn-new pull-right', :id => 'project-add-report' do %>
        <!-- <i></i>Add Report -->
      <%# end %>
      <%= link_to_add_fields "Add Report", f, :reports %>

      
    </div>
  </article>
  
  <article>
    <section>
      <!-- new report form -->

      <!-- new report form end -->
      <div id="project-report-listview">
        <table class="table" id="project-reports-table">
          <thead>
            <tr>
              <th>Report Title</th>
              <th>Created on</th>
              <th>Status</th>
              <th></th>
              <th>Updated on</th>
              <th>Editors</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= f.fields_for :reports do |r| %>
              <% unless f.object.new_record? %>
                <tr>
                  <td><%= r.input :name, :label => false %></td>
                  <td><%= r.object.created_at.strftime("%d/%m/%Y") %></td>
                  <td><%= r.object.report_state.name unless r.object.report_state.nil? %></td>
                  <td></td>
                  <td><%= r.object.updated_at.strftime("%d/%m/%Y") %></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
              <% else %>
                <%= render "report_fields", f: f %>  
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>

    </section>
  </article>

  <div class="form-actions">
    <%= f.button :submit, "Save", :class => 'btn-save pull-right' %>
    <a href="#" id="project-revert" class="btn pull-right">Revert</a>
  </div>

<% end %>

app/views/admin/projects/_report_fields.html.erb
<tr>
  <td><%= f.input :name, :label => false %></td>
  <td><%= f.input :created_at, as: :string, :label => false, :input_html => { :value => DateTime.now } %></td>
  <td>
    <%#= r.object.report_state.name unless r.object.report_state.nil? %>
    <%#= f.association :report_state, as: :string, :label => false, :input_html => { :value => DateTime.now } %>
    Commissioned
  </td>
  <td></td>
  <td><%= f.object.updated_at %></td>
  
  <td>
    <%= select_tag "project-new-report-type", options_from_collection_for_select(User.order(:username), "id", "username"),
             :prompt => "Select Editor", :class => 'form-control' %>
  </td>
  <td>
    <a href="#" class="link_destroy remove">Remove</a>
    <%#= link_to 'Destroy', report, method: :delete, :class => 'link_destroy',
          data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/admin/projects/edit.html.erb
<div class="page-header">
	<h1>Edit Project</h1>
	<%= link_to "back to list", :back,  :class => "btn-mini" %>
</div>

<div class="well">
	<h3><%= @project.name %></h3>

	<div class="action">
		<a href="#" class="btn btn-duplicate">Duplicate</a>
  	<a href="#" class="btn btn-publish"><i></i>Publish</a>
  	<a href="#" class="btn btn-export"><i></i>Export Data</a>
  	<%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' },
  		:class => 'btn'  %>
	</div>	
	
</div>
<%= render 'form' %>

<%#= link_to 'Show', @project %>
<%#= link_to 'Back', admin_projects_path %>

app/views/admin/projects/index.html.erb
<% content_for :sub_menu do %>
  <%= render "admin/shared/projects_sub_menu" %>
<% end %>

<div class="page-header">
  <h1>Projects</h1>
</div>

<div class="well">
  <section>
    <div class="table-search">
      <input type="text" placeholder="search" class="dataTable-search" />

      
    </div>
    <%= link_to "#", 
        :class => "btn btn-filter" do %>
        <i></i>Show Filter
    <% end %>

    <%= link_to new_admin_project_path, :class => "btn btn-new pull-right" do %>
      <i></i>New Project
    <% end %>
  </section>
</div>

<div class="well filters">
  <section>
      <div class="row">


        <div class="col-sm-2">
          <div class="ddl-sector">
            <%= select_tag "", options_from_collection_for_select(@companies, "id", "name"),
                 :class => 'form-control', :prompt => "Companies" %>
          </div>
        </div>

        

        <div class="col-sm-2">
          <div class="ddl-type">
            <select class="form-control">
                <option>Status</option>
                <option>Pdf</option>
                <option>CSV</option>
            </select>
          </div>
        </div>
      </div>  
      <div class="row">
        <div class="col-sm-6">
          <a href="#" class="btn btn-green btn-action-filter"><i></i>Filter</a>
          <a href="#" class="btn btn-reset"><i></i>Reset</a>
        </div>  
      </div>
  </section>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Publish date</th>
      <th>Ft index</th>
      <th>In result table</th>
      <th>Can compare</th>
      <th>Reports count</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= project.publish_date %></td>
        <td><%= project.ft_index %></td>
        <td><%= project.in_result_table %></td>
        <td><%= project.can_compare %></td>
        <td><%= link_to project.reports_count, admin_project_reports_path(project) %></td>
        <td><%= link_to 'Edit', edit_admin_project_path(project), :class => 'link_edit' %></td>
        <td><%= link_to 'Destroy', project, :class => 'link_destroy',
          method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/projects/new.html.erb
<div class="page-header">
	<h1>New project</h1>
</div>


<%= render 'form' %>

<%#= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @project.publish_date %>
</p>

<p>
  <strong>Ft index:</strong>
  <%= @project.ft_index %>
</p>

<p>
  <strong>In result table:</strong>
  <%= @project.in_result_table %>
</p>

<p>
  <strong>Can compare:</strong>
  <%= @project.can_compare %>
</p>

<p>
  <strong>Reports count:</strong>
  <%= @project.reports_count %>
</p>

<%= link_to 'Edit', edit_admin_project_path(@project) %> |
<%= link_to 'Back', admin_projects_path %>