config/routes.rb
Bc4::Application.routes.draw do

 

  namespace :admin do
    resources :report_tags
  end

  namespace :admin do
    resources :sub_metrics
  end

  
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :password_resets
  resources :users
  resources :newsletters

  

  match 'wed' => 'wed/wed#dashboard', via: :get
  match 'wed/dashboard' => 'wed/wed#dashboard', via: :get, :as => :wed_dashboard
  match 'wed/score-card' => 'wed/wed#score_card', via: :get, :as => :score_card
  match 'wed/latest-report' => 'wed/wed#latest_report', via: :get, :as => :latest_report
  match 'wed/progress-chart' => 'wed/wed#progress_chart', via: :get, :as => :progress_chart
  match 'wed/peer-comparison' => 'wed/wed#peer_comparison', via: :get, :as => :peer_comparison
  match 'wed/best-practice' => 'wed/wed#best_practice', via: :get, :as => :best_practice
  match 'wed/results-table' => 'wed/wed#results_table', via: :get, :as => :results_table
  match 'wed/consultancy' => 'wed/wed#consultancy', via: :get, :as => :wed_consultancy
  match 'wed/wen' => 'wed/wed#wen', via: :get, :as => :wed_wen

  match 'admin' => 'admin/admin#dashboard', via: :get, :as => :admin_dashboard
  match 'admin/advanced-search' => 'admin/admin#advanced_search', via: :get, :as => :admin_advanced_search
  match 'admin/manage-report/:id' => 'admin/reports#manage_report', via: :get, :as => :manage_report
  match 'admin/emails' => 'admin/system_emails#index', via: :get, :as => :admin_emails

  match 'admin/cmsdesk' => 'admin/cms_desk#index', via: :get, :as => :cms_desk
  match 'admin/cmsdesk/web' => 'web/pages#index', via: :get, :as => :cms_desk_web_pages
  match 'admin/cmsdesk/web/new' => 'web/pages#new', via: :get, :as => :cms_desk_new_web_page
  match 'admin/cmsdesk/web/:id/edit' => 'web/pages#edit', via: :get, :as => :cms_desk_edit_web_page
  match 'admin/cmsdesk/commentaries' => 'admin/commentaries#index', via: :get, :as => :cms_desk_commentaries
  match 'admin/cmsdesk/bctips' => 'admin/bctips#index', via: :get, :as => :cms_desk_bctips

  match 'wed/company-profile/:id' => 'wed/wed#company_profile', via: :get, :as => :company_profile
  match 'wed/account/my-peers' => 'wed/wed#my_peers', via: :get, :as => :my_peers
  match 'wed/account/my-account' => 'wed/wed#my_account', via: [:get], :as => :my_account
  match 'wed/account/my-account-update' => 'wed/wed#my_account_update', via: [:post], :as => :my_account_update

  match 'wed/search' => 'wed/wed#search', via: :get, :as => :wed_search
  match 'wed/advanced-search' => 'wed/wed#advanced_search', via: :get, :as => :wed_advanced_search

  match 'wed/latest_report/download_pdf' => 'admin/reports#generate_report_pdf', via: :get, :as => :download_report_pdf

  namespace :web do
    resources :widgets
    resources :pages, only: [:index, :new, :create]
    resources :pages, path: "", except: [:index, :new, :create]
  end

  namespace :admin do

    resources :users, :roles
    resources :system_emails

    resources :companies do
      collection do
        post :best_practice_all
      end

      resources :reports
    end

    resources :company_types, :company_statuses, :sectors, :regions, :countries, :subscriptions
    resources :metrics do
    end

    resources :reports do
      resources :notes
      resources :metrics
      resources :screengrabs

      collection do
      end
    end
    resources :projects do
      resources :reports
    end

    resources :report_states, :report_types, :report_tags
  
    resources :bctips, :commentaries

    resources :best_practices do
      resources :screengrabs  
    end
  end

  

    

  unless Web::Page.find_by_url("home").nil?
      root 'web/pages#show', :id => Web::Page.find_by_url("home").id
  else

    root 'web/pages#index'
  end

  get '*id', to: 'web/pages#show', as: :page

  

  
  
end

app/models/admin/report.rb
# == Schema Information
#
# Table name: reports
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  project_id     :integer
#  company_id     :integer
#  report_type_id :integer
#  publish_date   :date
#  approved       :boolean
#  user_id        :integer
#  created_at     :datetime
#  updated_at     :datetime
#

# TO DO ? HSTORE to store all the data after published

class Admin::Report < ActiveRecord::Base
	attr_accessible :id, :name, :project_id, :company_id, :publish_date, 
    :report_type_id, :created_at, :updated_at
	self.table_name = "reports"

  belongs_to :project, 
  	:class_name => "Admin::Project",
  	counter_cache: true
  belongs_to :company, 
  	:class_name => "Admin::Company",
  	counter_cache: true
  belongs_to :report_type, 
    :class_name => "Admin::ReportType"
  belongs_to :report_state,
    :class_name => 'Admin::ReportState'
  belongs_to :approver,
    :class_name => "User"
  
  # has_many :metrics,
  # 	:class_name => "Admin::Metric"	- wrong
  has_many :reports_metrics, :class_name => "ReportsMetric"
  has_many :metrics, -> { order('metrics.number DESC')}, through: :reports_metrics, 
          :class_name => "Admin::Metric"


  has_many :notes,
    :as => :note_source,
    :class_name => "Admin::Note"
	has_many :screengrabs,
    :as => :source,
    :class_name => "Admin::Screengrab"
    
  # Scopes
  scope :published, -> { where(published: :true) }  

  scope :created_by, lambda { |user|
    # includes(:assignee).
    # where('user_id = ? AND IS NOT NULL', user.id)
  }
  scope :approved_by, lambda { |user|
    # where('user_id = ? AND IS NOT NULL', user.id)
  }

  # after_create :send_email_to_editors, if: :author_wants_emails?,
  #   unless: Proc.new { |comment| comment.post.ignore_comments? }


  # TO do
  # scope - reports awaiting approvals
  # scopt - reports assigned to me


  def report_name
    unless publish_date.nil?
      "#{company.name} #{report_type.name} #{publish_date.strftime("%Y")}"
    else
      "#{company.name} #{report_type.name}"
    end
  end
  # to do - pending for publish reports( where containing project is not yet publishd -join project)
  # scope :pending_for_publish -> { }

  # methods
  def latest_reports
  	# find latest 10 reports order desc		
  end

  def latest_published_reports
    # find latest 10 published reports order desc   
  end

  def latest_published_reports company
    # find all reports by given company order by esc
    where(company_id: company.id).order(created_at: :desc)
  end

  def public_reports(company, type)
  	
  end	

end

app/models/admin/report_type.rb
# == Schema Information
#
# Table name: report_types
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  public         :boolean
#  notes          :text
#  exe_summary    :boolean
#  recommendation :boolean
#  best_practice  :boolean
#  supplementary  :boolean
#  created_at     :datetime
#  updated_at     :datetime
#

class Admin::ReportType < ActiveRecord::Base
	attr_accessible :id, :name, :public, :notes, :exe_summary, :recommendation, :best_practice, :supplementary
	self.table_name = "report_types"

	has_many :reports, :class_name => "Admin::Report"
	
	has_many :metric_report_types, :class_name => "Admin::MetricReportType"
  has_many :metrics, -> { order('metric_report_types.number ASC')}, through: :metric_report_types, 
  				:class_name => "Admin::Metric"

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController
  before_action :set_report, only: [:show, :edit, :update, :destroy, :manage_report]

  respond_to :pdf, :only => :generate_report_pdf


  def manage_report

    # to do:: check the report types to include extra tabs
    # @metrics = Admin::Metric.all    
    # @report_type_metrics = @report.report_type.metric_report_types.order(:number)
    @report_type_metrics = @report.reports_metrics.includes(:metric).order('metrics.number asc')
    # debugger
  end

  def generate_report_pdf
    
    # @report = params[:report_id]  
    # debugger
    @report = Admin::Report.find(811)

    respond_to do |format|
      format.pdf do
        pdf = ReportPdf.new(@report)
        
        send_data pdf.render, file_name: "report_name.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /reports
  # GET /reports.json
  def index
    # debugger
    
    @companies = Admin::Company.order(:name).all
    @report_types = Admin::ReportType.order(:name).all
    @projects = Admin::Project.order(:name).all
    # @reports = Admin::Report.all
  
    if params[:company_id].present?
      @reports = Admin::Report.where("company_id = ?", params[:company_id])
          
    
    elsif params[:project_id].present?
      @reports = Admin::Report.where("project_id = ?", params[:project_id])
          
    
    else
      
    @reports = Admin::Report.order(:created_at)
                
    end            

  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new

    # debugger
    @report = Admin::Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Admin::Report.new(report_params)
    # check there is project_id params- is required
    debugger
    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update

    # to do :: check report status

    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to admin_reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Admin::Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:admin_report).permit(:name, :project_id, :company_id, :publish_from, :publish_to)
    end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/_form.html.erb
<% content_for :sub_menu do %>
  <%= render "admin/shared/projects_sub_menu" %>
<% end %>

<%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :project %>
    <%= f.association :company %>
    <%= f.input :publish_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/reports/_view_report.html.erb
_view_report.html.erb

app/views/admin/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', admin_reports_path %>

app/views/admin/reports/index.html.erb
<% content_for :sub_menu do %>
  <%= render "admin/shared/projects_sub_menu" %>
<% end %>

<div class="page-header">
  <h1>Reports</h1>
</div>

<div class="well">
  <section>
    <div class="table-search">
      <input type="text" placeholder="search" />
      
    </div>
    <%= link_to "#", :class => "btn btn-filter" do %>
      <i></i>Show Filter
    <% end %>
  </section>
  
</div>

<div class="well filters">
  <section>
    <%= form_tag admin_reports_path, method: :get do |c| %>
      <div class="row">
        <div class="col-sm-3">
          <div class="ddl-sector">
            <%= select_tag "companies", options_from_collection_for_select(@companies, "id", "name"),
                 :class => 'form-control', :prompt => "Companies" %>
          </div>
        </div>

        <div class="col-sm-3">
          <div class="ddl-projects">
            <%= select_tag "project", options_from_collection_for_select(@projects, "id", "name"),
                 :class => 'form-control', :prompt => "Projects" %>
          </div>
        </div>

        <div class="col-sm-3">
          <div class="ddl-sector">
            <%= select_tag "report_types", options_from_collection_for_select(@report_types, "id", "name"),
                 :class => 'form-control', :prompt => "Report Types" %>
          </div>
        </div>

        <div class="col-sm-3">
          <div class="ddl-status">
            <%= select_tag "report_statues", 
              options_from_collection_for_select(Admin::ReportState.all, "id", "name"),
              :class => 'form-control', :prompt => "Report Status" %>
            <!-- <select class="form-control">
                <option>Status</option>
                <option>Pdf</option>
                <option>CSV</option>
            </select> -->
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3">
          <div class="ddl-assignee">
            <select class="form-control">
                <option>Assigned to</option>
                <option>Karen Admin</option>
                <option>Mali Editor</option>
            </select>
          </div>
        </div>

        <div class="col-sm-3">
          <%= text_field_tag(:published_from) %>
        </div>
        
        <div class="col-sm-3">
          <%= text_field_tag(:published_to) %>
        </div>

      </div>  

      <div class="row">
        <div class="col-sm-6">
          <%= button_tag(:type => "submit", :class => "btn btn-green btn-action-filter") do %>
            <i></i>Filter
          <% end %>
          <!-- <a href="#" class="btn btn-green btn-filter"><i></i>Filter</a> -->
          <a href="#" class="btn btn-reset"><i></i>Reset</a>
        </div>  
      </div>
    <% end %>
  </section>
</div>


<!-- <div class="pager">
  <section class="pager-info">
    <%#= page_entries_info @reports %>  
  </section>
  <section>
    <%#= will_paginate @reports, :next_label => 'Next', :previous_label => 'Previous' %>
  </section>  
</div>  -->   

<table class="table">
  <thead>
    <tr>
      <th>Name<span>drop</span></th>
      <th>Project</th>
      <th>Company</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td>
          <% unless report.name.blank? %>
            <%= report.name %>
          <% else %>
            <%= report.company.name  unless report.company.nil? %>
            <%= report.report_type.name unless report.report_type.nil? %>
            <%= report.publish_date.strftime("%Y") unless report.publish_date.nil? %>
          <% end %>
        </td>
        <td>
          <%  unless report.project.nil? %>
            <%= link_to report.project.name, edit_admin_project_path(report.project) %>
          <%# else %>
          <% end %>
        </td>
        <td><%= report.company.name unless report.company.nil? %></td>
        <td>
          <%= link_to 'Edit', manage_report_path(report), {:class => 'link_edit',
                :'data-toggle' => 'tooltip', :title => 'Edit' } %>
        </td>
        <td><%= link_to 'Destroy', report, :class => 'link_destroy',
             :title => 'Edit',
            method: :delete, data: { toggle: 'tooltip', confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- <div class="pager">
  <section class="pager-info">
    <%#= page_entries_info @reports %>  
  </section>
  <section>
    <%#= will_paginate @reports, :next_label => 'Next', :previous_label => 'Previous' %>
  </section>  
</div>     -->
<%#= link_to 'New Report', new_admin_report_path %>

app/views/admin/reports/manage_report.html.erb
<% content_for :sub_menu do %>
  <%= render "admin/shared/projects_sub_menu" %>
<% end %>

<div class="page-header">
	<h1>
		<%= @report.report_name %>
		<%#= @report.name %>
	</h1>
</div>

<div class="well">
	<section>
		
		<button class="btn-rpt-view" data-toggle="modal" data-target="#viewReport">
      <i></i>View
    </button>

    <button class="btn-rpt-submit">
      <i></i>Submit
    </button>

    <button class="btn-rpt-publish">
      <i></i>Publish
    </button>

    <button class="btn-rpt-unpublish">
      <i></i>Unpublish
    </button>

    <button class="btn-notes" data-toggle="modal" data-target="#report_notes_form">
      <i></i>Notes (<%= @report.notes.count %>)
    </button>

    <button class="btn-save">
      Save
    </button>
    
    <div class="ddl-download">
    	<select class="form-control">
	    	<option>Format</option>
	    	<option>Pdf</option>
	    	<option>CSV</option>
	    </select>
    </div>

    <button class="btn btn-download">
      <i></i>Download
    </button>
    

	</section>
</div>



<ul class="nav-tabs classic" id="report_tab">
  <li><a href="#overview" data-toggle="tab">Overview</a></li>
  <li><a href="#report" data-toggle="tab">Report</a></li>
</ul>


<!-- Tab panes -->
<div class="tab-content">
  
  <!-- report overview content -->
  <div class="tab-pane" id="overview">
  	

  	<%#= render "admin/reports/manage_report_overview" %>
  	<article>
  		<header>
  			<h4>Company</h4>
  		</header>
  		<section>
  			<%= @report.company.name %>
		  	<%= link_to @report.company.url, @report.company.url, :target => '_blank' %>
		  	<%= @report.company.country.name %>
		  	<%= @report.company.country.region.name %>
  		</section>
  		
  	</article>

  	<article>
  		<section>
  			<div class="panel-group" id="accordion">
				  <% @report_type_metrics.each do |report_metric| %>
				    <div class="panel panel-default">
				      <div class="panel-heading">
				        <h4 class="panel-title">
				          <a data-toggle="collapse" data-parent="#accordion" href="#<%= report_metric.id %>">
				            <%= report_metric.metric.name %>
				          </a>
				          <%#= link_to 'Edit', edit_admin_metric_path(metric) %>
				          <%#= link_to 'Destroy', metric, method: :delete, 
				            data: { confirm: 'Are you sure?' } %>
				        </h4>
				      </div>
				      <div id="<%= report_metric.id %>" class="panel-collapse collapse">

				        <div class="panel-body">
				          <table class="">
				          	<% report_metric.reports_sub_metrics.includes(:sub_metric).order('sub_metrics.number asc').each do |rpt_sub_metric| %>
						      		<tr>
						      			<td>
						      				<%= rpt_sub_metric.sub_metric.name %>
						      			</td>
						      		</tr>
						      		<% end %>
						      	</table>
				        </div>
				      </div>

				    </div>
				  <% end %>
				</div>

  				
  		</section>
  	</article>

  </div>
	
  <!-- report edit form content -->
  <%#= render "admin/reports/manage_report_form" %>
  <div class="tab-pane" id="report">

  	<div class="rpt-view-totalscore">
			<div class="total">Total Score [280]</div>
			<div class="scores">Score 210 (220)</div>
		</div>

  	<div class="nav nav-tabs" id="report-tabs">
			<ul>
				<% @width = 100.00/@report_type_metrics.count %>

				<% @report_type_metrics.each do |metric| %>
					<li style="width: <%= "#{@width}" + '%' %>"><a href="#<%= metric.metric.name.downcase.gsub(' ','-') %>" data-toggle="tab"><%= metric.metric.name %></a></li>
					
				<% end %>
			</ul>
		</div>		

		
			<div class="tab-content">
			<% @report_type_metrics.each do |report_type_metric| %>	
			
				<div class="tab-pane" id="<%= report_type_metric.metric.name.downcase.gsub(' ','-') %>">


					<div class="panel-group report-accordion" id="accordion">
						<div class="rpt-metric-score">
							<div class="name">
								<%= report_type_metric.metric.name %> [<%= report_type_metric.reports_sub_metrics.sum(:total_score) %>]
							</div>
							<div class="scores">Score 39 (41)</div>
						</div>

					<!-- CONSTRUCTION METRIC FORM START -->		
					
						<%# report_type_metric.metric.sub_metrics.each do |sub_metric| %>	
						<% report_type_metric.reports_sub_metrics.includes(:sub_metric).order('sub_metrics.number asc').each do |rpt_sub_metric| %>	
						  <div class="panel panel-default">
						    <div class="panel-heading">
						      <h4 class="panel-title">
						        <a data-toggle="collapse" data-parent="#accordion" href="#<%= rpt_sub_metric.id %>" class="collapsed">
						        	<%= report_type_metric.metric.number %>.<%= rpt_sub_metric.sub_metric.number %>
						          <%= rpt_sub_metric.sub_metric.name %>
						        </a>
						        <!-- <span>Score 11(13)</span> -->
						      </h4>
						    </div>
						    <div id="<%= rpt_sub_metric.id %>" class="panel-collapse collapse">
						      <div class="panel-body">

				        		<p>
							        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
							      </p>  
						        	

							      <div class="panel-slide row">
						        	<section>
						        		<div class="title">Notes(<%#= sub_metric.notes.count %>)</div>
						        		<div class="view-notes">
						        			<form>
						        				<textarea>
														</textarea>
						        				<button class="btn btn-save">Save Note</button>
						        			</form>

						        		</div>
						        	</section>
						        </div>

						        <div class="panel-section row">
						        	<section>
						        		<div class="title">Reference URL</div>
						        		<input type="text" width="300" />
						        	</section>
						        </div>

						        <!-- <div class="panel-section row">
						        	<section>

						        		<%# rpt_sub_metric.report_types_sub_metrics_questions.each do |question| %>
							        		<div class="title">Q: <%#= question.question.question %></div>
							        		<textarea class="ckeditor" name="editor">
							        		</textarea>
						        		<%# end %>

						        	</section>
						        </div> -->

						        <div class="panel-section row">
						        	<section>
						        		<div class="title">Screengrabs</div>

						        		<div class="col-sm-3">
						        			<figure>
						        				<a href="#">
						        					<img src="#" alt="" />
						        				</a>
						        				<figcaption>Fig1. - A view of the pulpit rock in Norway.</figcaption>
						        			</figure>
						        		</div>

						        		<div class="col-sm-3">
						        			<figure>
						        				<a href="#">
						        					<img src="#" alt="" />
						        				</a>
						        				<figcaption>Fig1. - A view of the pulpit rock in Norway.</figcaption>
						        			</figure>
						        		</div>

						        		<div class="col-sm-3">
						        			<figure>
						        				<a href="#">
						        					<img src="#" alt="" />
						        				</a>
						        				<figcaption>Fig1. - A view of the pulpit rock in Norway.</figcaption>
						        			</figure>
						        		</div>
						        	</section>
						        </div>


						        <div class="panel-section row">

						        	<section>
							        	<div class="title">Recommend</div>
							        	<textarea></textarea>
							        	<div class="title">Consider</div>
							        	<textarea></textarea>
							        </section>	
						        </div>

						        <div class="panel-section row">

						        	<section>
							        	<div class="title">Best Practice</div>
							        </section>
							        <table >
							        	<thead>
							        		<th>Company</th>
							        		<th>Title</th>
							        		<th>Manage</th>
							        	</thead>
							        	<tbody>
							        		<td>Company Name</td>
							        		<td>title</td>
							        		<td>manage</td>
							        	</tbody>
							        </table>	
						        </div>

						        <div class="panel-section row">

						        	<section>
							        	<div class="title">Tags</div>
							        	<%= select_tag "rpt-tag", options_from_collection_for_select(Admin::ReportTag.order(:name).all, 
							        			"id", "name"), :prompt => "Select", :multiple => 'true' %>
							        	<%#= f.collection_select :report_tag_ids, ReportTag.order(:name), :id, :name, {}, {multiple:true} %>
							        	
							        </section>

						        </div>

						        <div class="panel-section row">

						        	<section>
							        	<div class="title">Documents</div>		
							        	<ul class="rpt-doc-list">
							        		<li>
							        			<a href="#" title="title">Document Title (Format, KB)</a>
							        			<a class="link_remove pull-right">remove</a>
							        		</li>
							        		<li>
							        			<a href="#" title="title">Document Title (Format, KB)</a>
							        			<a class="link_remove pull-right">remove</a>
							        		</li>
							        	</ul>
							        		
							        </section>	
						        </div>
						        <div class="form-action">
						        	<a href="#" class="btn-save pull-right" >Save</a>
						        	<!-- <a href="#" class="btn pull-right">Clear</a> -->
						        </div>


						      </div>
						    </div>
						  </div>
						<% end %>
					</div>	
				</div>
				<% end %>
			</div>

				
			
  </div>
</div>

<% content_for :scripts do %>
	<script type="text/javascript">
		// CKEDITOR.replace( '.q1' );
		// CKEDITOR.replace( 'q2' );
		// CKEDITOR.replace( 'q3' );
	</script>  
<% end %>

<%#= render "shared/report_popup" %>
<%#= render "admin/shared/report_notes_popup" %>

app/views/admin/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_reports_path %>

app/views/admin/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @report.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @report.project.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @report.company.name %>
</p>
<p>
  <strong>Company logo:</strong>
  <%= image_tag(@report.company.logo.url(:normal)) %>
</p>

<p>
  <strong>Region:</strong>
  <%= @report.company.country.region.name %>
</p>


<p>
  <strong>Country:</strong>
  <%= @report.company.country.name %>
</p>

<p>
  <strong>Published Date:</strong>
  <%= @report.publish_date %>
</p>


<%= link_to 'Edit', edit_admin_report_path(@report) %> |
<%= link_to 'Back', admin_reports_path %>